### PR TITLE
Updates the resources from json to not have trailing /

### LINKED ISSUE #75: Calling `ClassLoader#getResource` with leading slash doesn't work
### Describe the bug
After the last round of updates on the CLion IDE, I get the following error message from within the IDE after it started:

```
Calling `ClassLoader#getResource` with leading slash doesn't work; strip

com.intellij.diagnostic.PluginException: /icons-dark/actions/16/configure.svg [Plugin: com.github.l0drex.intellijkdebreezetheme]
	at com.intellij.ide.plugins.cl.PluginClassLoader.doFindResource(PluginClassLoader.java:548)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:456)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1403)
	at com.intellij.ui.RasterizedImageDataLoader.getURL(RasterizedImageDataLoader.kt:67)
	at com.intellij.openapi.util.IconLoader.loadCustomVersion(IconLoader.java:86)
	at com.intellij.openapi.util.IconLoader.loadCustomVersionOrScale(IconLoader.java:114)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.toolbar.HeaderToolbarButtonLook.scaleIcon(HeaderToolbarButtonLook.kt:53)
	at com.intellij.openapi.wm.impl.customFrameDecorations.header.toolbar.HeaderToolbarButtonLook.paintIcon(HeaderToolbarButtonLook.kt:33)
	at com.intellij.openapi.actionSystem.impl.ActionButton.paintButtonLook(ActionButton.java:430)
	at com.intellij.openapi.actionSystem.impl.ActionButton.paintComponent(ActionButton.java:404)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1122)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.lambda$paint$3(ActionToolbarImpl.java:337)
	at com.intellij.util.animation.AlphaAnimationContext.paintWithComposite(AlphaAnimationContext.kt:50)
	at com.intellij.util.animation.AlphaAnimationContext.paint(AlphaAnimationContext.kt:40)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.paint(ActionToolbarImpl.java:337)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1131)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5319)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1347)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5267)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5077)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:882)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:865)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:865)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:838)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:787)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1909)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:475)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

### Affected theme
- [x] Dark theme
- [ ] Light theme

### Desktop
 - _Plugin Version:_ v0.3.3
 - _IDE version:_ CLion 2022.3.1

### PR DESCRIPTION
**Pull request by alevalv**
Bump minimum build to 223
Bump intellij plugin version
Bump java to 17

Should fix #75 

Tested locally with Build #IU-223.8617.56, built on January 26, 2023 2022.3.2

### CODE REVIEW

**Comment by fschwa** [comment]
Do you know what the Qodana error 7 means?

**Comment by alevalv** [comment]
no, I researched a bit on that and it seems like a quality control step configured by the github actions template, If I run the target locally it works, I updated the actions to use the same version as the template repo to see if it works.

**Comment by fschwa** [comment]
Nice, thanks for retesting. :)
I hope this will be merged soon.

**Comment by l0drex** [comment]
Thanks! Looks good, I will make a new release :+1:

**Pull request merged**
